### ISSUE TITLE
review discourse 

### ISSUE THREAD

**Issue by gilgamezh** [PyAmsterdam/py-meetups#20]
- review if we can use Discourse to have a modern mailing list + forum for discussions.

**Comment by gilgamezh** [comment]
tl;dr: discourse will cost 100/month or 50/month if we have an NGO

https://www.discourse.org/pricing

```
If you are legally recognized as a non-profit organization that is exempt from federal taxes, we offer a 50% discount. These discounts apply only to our standard and business plans, and must be paid through a debit/credit card monthly or annually. Please contact us after starting your trial and we’ll add the discount to your account.
```
I think a really good option would try to have our own "sub-forum" in the official python discourse. I'll write to them to see if that's possible.

**Comment by gilgamezh** [comment]
I asked in the official python discourse: https://discuss.python.org/t/local-community-category/2125

**Comment by 1oglop1** [comment]
Yeah it might be enough to reuse their space if possible, so we could just get our own section.

**Comment by 1oglop1** [comment]
@gilgamezh Any progress here?

**Comment by gilgamezh** [comment]
https://pyamsterdam.discourse.group  <-- pending to release!
