### ISSUE TITLE
Memory address in python!

### ISSUE THREAD

**Issue by mridubhatnagar** [PyAmsterdam/py-meetups#36]
The intent of this talk is to understand the following mentioned things.

- what is id?
- why are list, dicts mutable? While strings, tuples immutable. Through examples.
- a,b = 1, 1? Whether this leads to a single memory reference id or 2 different memory reference id.
-  difference between == and is?
- example showing  * operator which copies the memory references. 

Slides - https://docs.google.com/presentation/d/1gfZXB1uyGkL9OHSkdD8RZE6vGZ1ZJpsrhhc8tq3MYyk/edit?usp=sharing

**Comment by gilgamezh** [comment]
I moved the content of this issue to our form 
https://docs.google.com/forms/d/e/1FAIpQLSdkM1iWSMytaz99_Wkxjd5FtERDyiZjyxz7WmP8MT7SxhQCMg/viewform
