### ISSUE TITLE
[Lightning Talk] - Sorting

### ISSUE THREAD

**Issue by mridubhatnagar** [PyAmsterdam/py-meetups#37]
A short 5 min lightning talk proposal.

- Ways of sorting in Python. List.sort() and sorted()?
- Difference between list.sort() and sorted()?
- What needs to be used when?
- using sorted by importing it from another library?
- Examples and relating everything with memory address.
- Which sorting algorithm does List.sort() use?

**Comment by gilgamezh** [comment]
@mridubhatnagar please you have to propose this one during the meetup. We are going to share a google spreadsheet at the begging.

**Comment by mridubhatnagar** [comment]
@gilgamezh hey sorry, saw this just now. Didn't get you?
